---
title: "Mapping_figure1_presentation"
author: "Lia Domke"
date: "9/17/2024"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2) # used
library(ggtext) # used
library(raster) # used
library(sf) # used 
library(rnaturalearth) #used
# if rnaturalearth can't be loaded, try:
#install.packages("rnaturalearthhires", repos = "https://ropensci.r-universe.dev", type = "source")

library(dplyr) # used
library(tidyr)
library(kableExtra)
library(ggspatial) # used, provides scale bar

```


# read in data
```{r}
ak <- st_read(dsn = "Manuscript_scripts&data/Mapping_shapefiles_Figure1/",
              layer = "AK_shapefile")

canada <- st_read(dsn = "Manuscript_scripts&data/Mapping_shapefiles_Figure1/",
                  layer = "Canadian_provinces")

zos <- st_read(dsn = "Manuscript_scripts&data/Mapping_shapefiles_Figure1/",
               layer = "Difference_ZOS-SBR_060623-updated")

sbr <- st_read(dsn = "Manuscript_scripts&data/Mapping_shapefiles_Figure1/",
               layer = "Difference_SBR-ZOS_060623-updated")

rivers <- st_read(dsn = "Manuscript_scripts&data/Mapping_shapefiles_Figure1/",
                  layer = "anadromous_streams_pow_obj2")

sites17 <- st_read(dsn = "Manuscript_scripts&data/Mapping_shapefiles_Figure1/",
                   layer = "chp1obj2_sites2017")

sites19 <- st_read(dsn = "Manuscript_scripts&data/Mapping_shapefiles_Figure1/",
                   layer = "chp1obj2_sites2019")

sitesobj1 <- st_read(dsn = "Manuscript_scripts&data/Mapping_shapefiles_Figure1/",
                     layer = "chp1obj1_sites")
```

#plot theme
```{r theme settings, include=FALSE}
# Creates custom base plot theme that can adjust every graph that you use plot_theme for!

plot_theme <- function() {
  theme_bw(base_size = 24, base_family = "Calibri") %+replace%
    theme(panel.background  = element_blank(),
            plot.background = element_rect(fill="white", colour=NA), 
            legend.background = element_rect(fill="transparent", colour=NA),
            legend.key = element_rect(fill="transparent", colour=NA),
            panel.grid.major = element_blank(), 
            panel.grid.minor = element_blank())
}

# to use ggsave and export plots include argument 'device=cario_pdf' e.g.: 
# ggsave("name.pdf", device=cairo_pdf, width = 6, height = 6)
```

# creating global label fxn 
```{r adding global label}
add_global_label <- function(pwobj, Xlab = NULL, Ylab = NULL, Xgap = 0.03, Ygap = 0.03, ...) {
    ylabgrob <- patchwork::plot_spacer()
    if (!is.null(Ylab)) {
        ylabgrob <- ggplot() +
            geom_text(aes(x = .5, y = .5), label = Ylab, parse = T,
                      angle = 90, ...) +
            theme_void()
    }
    if (!is.null(Xlab)) {
        xlabgrob <- ggplot() +
            geom_text(aes(x = .5, y = 0.5), label = Xlab, parse = TRUE, ...) +
            theme_void()
    }
    if (!is.null(Ylab) & is.null(Xlab)) {
        return((ylabgrob + patchworkGrob(pwobj)) + 
            patchwork::plot_layout(widths = 100 * c(Ygap, 1 - Ygap)))
    }
    if (is.null(Ylab) & !is.null(Xlab)) {
        return((ylabgrob + pwobj) + 
            (xlabgrob) +
            patchwork::plot_layout(heights = 100 * c(1 - Xgap, Xgap),
                                   widths = c(0, 100),
                                   design = "
                                   AB
                                   CC
                                   "
            ))
    }
    if (!is.null(Ylab) & !is.null(Xlab)) {
        return((ylabgrob + pwobj) + 
            (xlabgrob) +
            patchwork::plot_layout(heights = 100 * c(1 - Xgap, Xgap),
                                   widths = 100 * c(Ygap, 1 - Ygap),
                                   design = "
                                   AB
                                   CC
                                   "
            ))
    }
    return(pwobj)
}

```

# Inset map
```{r}
world <- ne_countries(scale = 10, returnclass = "sf")
usa <- ne_states("United States of America", returnclass = "sf") # simple features
ak.small <- subset(usa, name == "Alaska") %>% # Subset ak from the usa object for small AK inset
  st_transform(., crs = st_crs(26908))


canada.crop <- st_transform(canada, crs = st_crs(26908)) %>%
  st_crop(., sf::st_bbox(ak.small))
  
  
  #st_crop(canada, xmin = -120, xmax = -150,
                     #  ymin = 51.21, ymax = 71.4) %>%


inset <- ggplot() +
  geom_sf(ak.small, mapping = aes(), fill = "#999999", color = "black") +
  geom_sf(canada.crop, mapping = aes(), fill = "#5e5e5e", color = "black") +
  coord_sf(xlim = c(-2003837, 946671), ylim = c(5964637, 8153307), 
           expand = FALSE) + # controlling axis to disregard dateline
  geom_rect(aes(xmin = sf::st_bbox(st_transform(sitesobj1, crs = st_crs(26908)))[c(1)],
                xmax = sf::st_bbox(st_transform(sitesobj1, crs = st_crs(26908)))[c(3)],
                ymin = sf::st_bbox(st_transform(sitesobj1, crs = st_crs(26908)))[c(2)],
                ymax = sf::st_bbox(st_transform(sitesobj1, crs = st_crs(26908)))[c(4)]),
            color = "red", fill = NA, linewidth = 2) + # creates red box around region equavalent to the spatial extent of sitesobj1 bbox
  geom_text(mapping = aes(x = -365742.4, y = 7333075), label = "Alaska", size = 4) +
  geom_text(mapping = aes(x = 489556.3, y = 7021835), label = "Canada", size = 4) + #7021835
  theme_classic() +
  theme(axis.title = element_blank(),  # Removing remnants of axis title, text, tick marks,
        axis.text = element_blank(),  # lines, and changing plot background to transparent,
        axis.ticks = element_blank(), # and also creating black border around AK map
        axis.line = element_blank(),
        plot.background = element_rect(fill = "transparent", colour = NA),
        panel.border = element_rect(colour = "black", fill = NA, size = 0.75)) +
  annotation_scale(text_family = "Calibri", text_cex = 1.5, line_width = 2)
  #ggsn::scalebar(location = "bottomleft", dist = 500, dist_unit = "km", transform = F,
  #               x.min = -1554768, x.max = -183173.4, y.min = 6035655, y.max = 6209974, 
  #               st.bottom = FALSE, height = 0.3, st.dist = 0.5, st.size = 6)


```


# Main map 
## Objective 1 map
```{r}
sitesobj1.26908 <- st_transform(sitesobj1, crs = st_crs(26908)) %>%
  dplyr::select(SiteID, Location, Habitat, geometry) %>%
  arrange(Habitat) %>%
  distinct()

# we need to get a better extent to crop the shapefiles by 
ak.crop2 <- ak %>%
  st_transform(., crs = st_crs(26908)) %>%
  st_crop(ak, y = sf::st_bbox(zos)) %>% # limit it larger than the target distance
  st_simplify()

# this takes awhile to run 
#plot(ak.crop2$geometry)
#drawExtent()
#st_crop(ak, xmin = 513765.8, xmax = 790892.3,
#          ymin = 6054378, ymax = 6247162)

# create dataframe with labels we can to include
ak.crop.wgs <- ak.small %>%
  st_crop(., y = sf::st_bbox(ak.crop2)) %>%
  st_transform(., crs = st_crs(4326))

#plot(ak.crop.wgs$geometry)
#drawExtent()

labels <- data.frame(
  Latitude = c(55.72174, 55.62174, 54.74320, 55.56765, 55.46765, 55.69219),
  Longitude = c(-132.8007,-132.8007, -131.3829, -131.3543, -131.3543, -134.2992),
  Text = c("Prince of Wales", "Island","Dixon Entrance", "Revillagigedo", "Island", "Gulf of Alaska"))

labels.prj <- st_as_sf(labels, coords = c("Longitude", "Latitude"), crs = 4326) %>%
  st_transform(., crs = st_crs(26908))

ak.crop <- ak %>%
  st_transform(., crs = st_crs(26908)) %>%
  st_crop(ak, xmin = 513765.8, xmax = 760892.3,
          ymin = 6054378, ymax = 6247162)


#ggplot() + 
#  geom_sf(ak.crop, mapping = aes())

canada.crop.proj <- st_transform(canada.crop, crs = st_crs(26908)) %>%
  st_crop(., y = sf::st_bbox(ak.crop))


zos.red <- zos %>% 
  filter(ZOS == "C") %>%
  st_crop(., y = sf::st_bbox(ak.crop)) %>%
  dplyr::select(c(OBJECTID, geometry)) %>%
  mutate(Habitat = "zostera")

habitat.shz <- sbr %>%
  mutate(SBR = ifelse(SBR == "c" | SBR == "C", "C", SBR)) %>%
  filter(SBR == "C") %>%
  st_crop(., y = sf::st_bbox(ak.crop)) %>%
  dplyr::select(c(OBJECTID, geometry)) %>%
  mutate(Habitat = "sbr_kelp") %>%
  rbind(zos.red)



obj1_map <- ggplot() +
  #geom_sf(canada.crop.proj, mapping = aes(), fill = "#999999") +
  geom_sf(habitat.shz, mapping = aes(color = Habitat), key_glyph = "rect", linewidth = 2) +
  geom_sf(ak.crop, mapping = aes(), fill = "#999999") +
  geom_sf(sitesobj1.26908, mapping = aes(fill = Habitat, shape = Habitat, size = Habitat), 
          color = "black") +
  scale_color_manual(values = c("#327610", "#E4572E"),
                     labels = c("Continuous *Zostera marina*",
                                "Continuous soft brown kelps"),
                     name = "Legend") +
  scale_shape_manual(values = c(21, 24),
                     labels = c("Eelgrass sites",
                                "Understory kelp sites"),
                     name = NULL) +
  scale_fill_manual(values = c("#327610", "#E4572E"),
                    labels = c("Eelgrass sites",
                               "Understory kelp sites"),
                    name = NULL) +
  scale_size_manual(values = c(5,4),
                    labels = c("Eelgrass sites",
                               "Understory kelp sites"),
                    name = NULL) +
  coord_sf(expand = FALSE) +
  labs(x = "Longitude", y = "Latitude") +
  geom_sf_label(labels.prj, mapping = aes(label = Text), family = "Calibri", size = 6) +
  plot_theme() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.22,0.18),
        legend.text = element_markdown(size = 15),
        legend.spacing.y = unit(0, "cm"),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))


#obj1_map

#ggsave("Manuscript_scripts&data/Figures&Tables/obj1_map.png", height = 12, width = 9)
```

## Objective 2
```{r}
rivers.proj <- st_transform(rivers, crs = 26908) #%>%
  #st_crop(., xmin = 520737.6, xmax = 709106.6,
  #        ymin = 6065835.4, ymax = 6234545.3)


# combine and transform the sites
sites17.red <- sites17 %>%
  dplyr::select(site_ID, year, geometry) %>%
  distinct()

sites17.red.df <- st_drop_geometry(sites17.red)

sites <- sites19 %>%
  dplyr::select(site_ID, year, geometry) %>%
  distinct() %>%
  rbind(sites17.red) %>%
  st_transform(., crs = st_crs(26908))
  

obj2_map <- ggplot() +
  geom_sf(ak.crop, mapping = aes(), fill = "#999999") +
  #geom_sf(canada.crop.proj, mapping = aes(), fill = "#999999") +
  geom_sf(rivers.proj, mapping = aes(), color = "blue") +
  geom_sf(sites, mapping = aes(color = as.factor(year), shape = as.factor(year),
                               size = as.factor(year))) +
  scale_color_manual(values = c("#58355E", "#F8CC07"), name = "Legend") +
  scale_shape_manual(values = c(17, 19), "Legend") +
  scale_size_manual(values = c(4, 5), "Legend") +
  #ggsn::scalebar(dist = 40, dist_unit = "km",
  #               x.min = , x.max = , y.min = , y.max = ,
  #               transform = F, st.bottom = F, height = 0.03, st.dist = 0.05, st.size = 8) +
  coord_sf(expand = F) +
  plot_theme() +
  labs(y = NULL, x = "Longitude") +
  annotation_scale(text_family = "Calibri", text_cex = 2, line_width = 3) +
  geom_sf_label(labels.prj, mapping = aes(label = Text), family = "Calibri", size = 6) +
  theme(legend.position = "inside",
        legend.position.inside = c(0.1,0.18),
        legend.text = element_text(size = 18),
        legend.spacing.y = unit(0, "cm"),
        axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```

## full figure 1
```{r}
library(patchwork)
obj2_inset <- obj2_map + inset_element(inset, 0.64, 0.64, 1, 1, align_to = "plot", ignore_tag = TRUE)

map1 <- obj1_map + obj2_inset +
  plot_layout(nrow = 1, ncol = 2, axes = "collect", axis_titles = "collect")


#ggsave("Manuscript_scripts&data/Figures&Tables/Obj2_inset.png",plot = obj2_inset, height = 12, width =9)

#ggsave("Manuscript_scripts&data/Figures&Tables/Figure1_map.png", plot = map1,
#       height = 12, width = 18)

```

## Obj1/2 stacked
```{r}
obj1_map_stack <- ggplot() +
  #geom_sf(canada.crop.proj, mapping = aes(), fill = "#999999") +
  geom_sf(habitat.shz, mapping = aes(color = Habitat), key_glyph = "rect", linewidth = 2) +
  geom_sf(ak.crop, mapping = aes(), fill = "#999999") +
  geom_sf(sitesobj1.26908, mapping = aes(fill = Habitat, shape = Habitat), 
          color = "black", size = 5) +
  scale_color_manual(values = c("#327610", "#E4572E"),
                     labels = c("Continuous *Zostera marina*",
                                "Continuous soft brown kelps"),
                     name = "Legend") +
  scale_shape_manual(values = c(21, 24),
                     labels = c("Eelgrass sites",
                                "Understory kelp sites"),
                     name = NULL) +
  scale_fill_manual(values = c("#327610", "#E4572E"),
                    labels = c("Eelgrass sites",
                               "Understory kelp sites"),
                    name = NULL) +
  coord_sf(expand = FALSE) +
  labs(x = NULL , y = NULL) +
  geom_sf_label(labels.prj, mapping = aes(label = Text), family = "Calibri", size = 6) +
  plot_theme() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.22,0.18),
        legend.text = element_markdown(size = 15),
        legend.spacing.y = unit(0, "cm"),
         axis.text.x = element_blank())


############ objective 2 #############
obj2_map_stack <- ggplot() +
  geom_sf(ak.crop, mapping = aes(), fill = "#999999") +
  #geom_sf(canada.crop.proj, mapping = aes(), fill = "#999999") +
  geom_sf(rivers.proj, mapping = aes(), color = "blue") +
  geom_sf(sites, mapping = aes(color = as.factor(year), shape = as.factor(year),
                               size = as.factor(year))) +
  scale_color_manual(values = c("#58355E", "#F8CC07"), name = "Legend") +
  scale_shape_manual(values = c(17, 19), "Legend") +
  scale_size_manual(values = c(4, 5), "Legend") +
  #ggsn::scalebar(dist = 40, dist_unit = "km",
  #               x.min = , x.max = , y.min = , y.max = ,
  #               transform = F, st.bottom = F, height = 0.03, st.dist = 0.05, st.size = 8) +
  coord_sf(expand = F) +
  plot_theme() +
  labs(y = NULL, x = "Longitude") +
  annotation_scale(text_family = "Calibri", text_cex = 2, line_width = 3) +
  geom_sf_label(labels.prj, mapping = aes(label = Text), family = "Calibri", size = 6) +
  theme(legend.position = "inside",
        legend.position.inside = c(0.1,0.18),
        legend.text = element_text(size = 18),
        legend.spacing.y = unit(0, "cm"))



map_together <- obj1_map_stack /
  obj2_map_stack

labeled_map <- add_global_label(map_together, 
                                Ylab = "Longitude")

#ggsave("Manuscript_scripts&data/Figures&Tables/Figure1_map_stacked")
```




